suites:
    kawaii_suite:
        namespace: kawaii
        psr4_prefix: kawaii
        spec_prefix: spec
        src_path: %paths.config%/src
        spec_path: %paths.config%

formatter.name: progress
code_generation: true
stop_on_failure: true